FROM mcr.microsoft.com/dotnet/sdk:10.0  AS base
USER $APP_UID
EXPOSE 8080
EXPOSE 8081

COPY bin/Release/net10.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p 00354343-fff6-49d4-86ce-bbcf9c8da1eb
RUN chmod 644 openiddict.pfx

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "Tx.Blog.HttpApi.Host.dll"]